
#define COB_X "location/x"
#define COB_Y "location/y"
#define COB_ROTATION "location/rotation"
#define COB_X_VEL "location/xVel"
#define COB_Y_VEL "location/yVel"
#define COB_LEFT_DISTANCE "location/left-distance"
#define COB_RIGHT_DISTANCE "location/right-distance"
#define COB_MAIN_ARM_ROTATION "arm/main-arm/rotation"
#define COB_WRIST_ROTATION "arm/wrist/rotation"
#define COB_VACUUM "arm/wrist/vacuum"
#define COB_HATCH "arm/wrist/is-hatch"
#define COB_SANDSTORM "robot/is-sandstorm"
#define COB_TELEOP "robot/is-teleop"
#define COB_ENABLED "robot/is-enabled"
#define COB_ALLIANCE_COLOR "robot/alliance-color"
#define COB_FIELD_ORIENTED "robot/is-field-oriented"
#define COB_TIME "fms/time-left"
#define COB_RED "fms/is-red" 

//arm
#define COB_ARM_CARGO_ROCKET_HIGH "/cob/arm-position/rocket-high"
#define COB_ARM_CARGO_ROCKERT_MID "/cob/arm-position/rocket-mid"
#define COB_ARM_CARGO_ROCKET_LOW "/cob/arm-position/rocket-low"
#define COB_ARM_CARGO_GROUND "/cob/arm-position/cargo/ground"
#define COB_ARM_CARGO_SHIP "/cob/arm-position/cargo/ship"
#define COB_ARM_HATCH_LOW "/cob/arm-position/hatch/low"
#define COB_ARM_HATCH_MID "/cob/arm-position/hatch/mid"
#define COB_ARM_HATCH_HIGH  "/cob/arm-position/hatch/high"
#define COB_ARM_SECURE "/cob/arm-position/secure"
#define COB_ARM_ALLEYOOP "/cob/arm-position/alley-oop"


//wrist
#define COB_WRIST_CARGO_ROCKET_HIGH "/cob/arm-position/rocket-high"
#define COB_WRIST_CARGO_ROCKET_MID "/cob/arm-position/rocket-mid"
#define COB_WRIST_CARGO_ROCKET_LOW "/cob/arm-position/rocket-low"
#define COB_WRIST_CARGO_GROUND "/cob/arm-position/cargo/ground"
#define COB_WRIST_CARGO_SHIP "/cob/arm-position/cargo/ship"
#define COB_WRIST_HATCH_LOW "/cob/arm-position/hatch/low"
#define COB_WRIST_HATCH_MID "/cob/arm-position/hatch/mid"
#define COB_WRIST_HATCH_HIGH "/cob/arm-position/hatch/high"
#define COB_WRIST_SECURE "/cob/arm-position/secure"
#define COB_WRIST_ALLEYOOP "/cob/arm-position/alley-oop"