#define OI_ARM_POSITION_LOW 1
#define OI_ARM_POSITION_MEDUIM 2
#define OI_ARM_POSITION_HIGH 9

#define OI_ARM_POSITION_CARGO_HOLD 3
#define OI_ARM_POSITION_CARGO_GROUND 10

#define OI_DRIVE_FOD_TOGGLE 1
#define OI_DRIVE_ALIGN_TOGGLE 7

#define OI_ARM_MANUAL_MODE 9
#define OI_ARM_V_MODE 8

#define OI_ARM_POSITION_SLIDER 1
#define OI_WRIST_POSITION_SLIDER 2

#define OI_CLIMB 0
